-- Tabela com dados brudos
CREATE TABLE prninfo (
        id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        time TEXT NOT NULL,
        prn INTEGER NOT NULL,
        snr REAL,
        azi REAL,
        elev REAL,
        lat REAl,
        long REAL
);

-- Tabela com os índices calculados
CREATE TABLE prnindices (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    prn INTEGER NOT NULL,
    mediasnr REAL,
    mediaazi REAL,
    mediaelev REAL,
    tinicial TEXT NOT NULL,
    tfinal TEXT NOT NULL,
    dpsnr REAL,
    s4 REAL NOT NULL
);

-- GENERATED BY PRISMA

-- CreateTable
CREATE TABLE "User" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nome" TEXT NOT NULL,
    "nickname" TEXT,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "administrator" BOOLEAN NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
